language: generic

services:
  - docker

before_install:
  - docker build -t stathisdim/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stathisdim/client-test npm test

after_success:
  - docker build -t stathisdim/multi-client ./client
  - docker build -t stathisdim/multi-server ./server
  - docker build -t stathisdim/multi-worker ./worker
  - docker build -t stathisdim/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push stathisdim/multi-client
  - docker push stathisdim/multi-server
  - docker push stathisdim/multi-worker
  - docker push stathisdim/multi-nginx